create table notification_requests (
    id bigint generated by default as identity,
    recipient_id varchar(100) not null,
    notification_type varchar(80) not null,
    event_id varchar(150) not null,
    requested_channel varchar(40) not null,
    reference_data_json text not null,
    created_at timestamp not null,
    updated_at timestamp not null,

    primary key (id),
    constraint uk_notification_request_dedup
        unique (recipient_id, notification_type, event_id)
);

create table notification_deliveries (
    id bigint generated by default as identity,
    notification_request_id bigint not null,
    channel varchar(40) not null,
    status varchar(30) not null,
    attempt_count integer not null default 0,
    max_attempts integer not null default 5,
    available_at timestamp not null,
    lock_owner varchar(100),
    locked_until timestamp,
    last_failure_type varchar(30),
    last_failure_code varchar(100),
    last_failure_message varchar(1000),
    succeeded_at timestamp,
    failed_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,

    primary key (id),
    constraint fk_notification_delivery_request
        foreign key (notification_request_id)
        references notification_requests (id),
    constraint uk_notification_delivery_channel
        unique (notification_request_id, channel)
);

create table notification_attempts (
    id bigint generated by default as identity,
    notification_delivery_id bigint not null,
    attempt_no integer not null,
    result varchar(30),
    failure_type varchar(30),
    failure_code varchar(100),
    failure_message varchar(1000),
    worker_id varchar(100),
    started_at timestamp not null,
    finished_at timestamp,

    primary key (id),
    constraint fk_notification_attempt_delivery
        foreign key (notification_delivery_id)
        references notification_deliveries (id),
    constraint uk_notification_attempt_no
        unique (notification_delivery_id, attempt_no)
);

create table notification_inboxes (
    id bigint generated by default as identity,
    notification_delivery_id bigint not null,
    recipient_id varchar(100) not null,
    title varchar(200) not null,
    message varchar(1000) not null,
    visible_at timestamp not null,
    read_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,

    primary key (id),
    constraint fk_notification_inbox_delivery
        foreign key (notification_delivery_id)
        references notification_deliveries (id),
    constraint uk_notification_inbox_delivery
        unique (notification_delivery_id)
);

create index idx_notification_delivery_polling
    on notification_deliveries (status, available_at);

create index idx_notification_delivery_processing_timeout
    on notification_deliveries (status, locked_until);

create index idx_notification_attempt_delivery
    on notification_attempts (notification_delivery_id, attempt_no);

create index idx_notification_inbox_recipient_read
    on notification_inboxes (recipient_id, read_at, visible_at);
