alter table notification_deliveries
    add column retry_cycle integer not null default 0;

alter table notification_deliveries
    add column manual_retry_count integer not null default 0;

alter table notification_attempts
    add column retry_cycle integer not null default 0;

alter table notification_attempts
    drop constraint uk_notification_attempt_no;

alter table notification_attempts
    add constraint uk_notification_attempt_no
        unique (notification_delivery_id, retry_cycle, attempt_no);

create table notification_manual_retries (
    id bigint generated by default as identity,
    notification_delivery_id bigint not null,
    retry_cycle integer not null,
    requested_by varchar(100) not null,
    reason varchar(1000),
    previous_status varchar(30) not null,
    previous_attempt_count integer not null,
    previous_failure_type varchar(30),
    previous_failure_code varchar(100),
    previous_failure_message varchar(1000),
    requested_at timestamp not null,
    created_at timestamp not null,

    primary key (id),
    constraint fk_notification_manual_retry_delivery
        foreign key (notification_delivery_id)
        references notification_deliveries (id),
    constraint uk_notification_manual_retry_cycle
        unique (notification_delivery_id, retry_cycle)
);

create index idx_notification_attempt_delivery_cycle
    on notification_attempts (notification_delivery_id, retry_cycle, attempt_no);

create index idx_notification_manual_retry_delivery
    on notification_manual_retries (notification_delivery_id, retry_cycle);
